version: "3"

services:
  frontend:
    image: test-frontend:1.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    build: ./frontend
    # container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    image: test-backend:1.0
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    build: ./backend
    # container_name: backend
    ports:
      - "7000:7000"
    networks:
      - webnet
networks:
  webnet: