version: "3"

services:
  frontend:
    image: test-frontend:1.0
    build: ./frontend
    container_name: test-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    image: test-backend:1.0
    build: ./backend
    container_name: test-backend
    ports:
      - "7000:7000"
    networks:
      - webnet
networks:
  webnet: